-- Password setup without email links or OTPs.
--
-- An admin receives a high-entropy temporary password exactly once. Only its bcrypt hash is
-- stored. It is tied to one invitee, expires after 72 hours, is consumed on successful claim,
-- and is temporarily locked after repeated failures. Knowing an invitee's email is therefore
-- not enough to take over the account.

CREATE TABLE IF NOT EXISTS public.onboarding_temp_passwords (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    password_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    failed_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamptz,
    generated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT onboarding_temp_password_attempts_nonnegative CHECK (failed_attempts >= 0)
);

CREATE TABLE IF NOT EXISTS public.onboarding_temp_password_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    event_type text NOT NULL CHECK (event_type IN ('issued', 'consumed')),
    actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.onboarding_temp_passwords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.onboarding_temp_password_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.onboarding_temp_passwords
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.onboarding_temp_password_events
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.onboarding_temp_password_events_id_seq
    FROM PUBLIC, anon, authenticated;

CREATE INDEX IF NOT EXISTS onboarding_temp_passwords_expiry_idx
    ON public.onboarding_temp_passwords (expires_at)
    WHERE consumed_at IS NULL;

CREATE INDEX IF NOT EXISTS onboarding_temp_password_events_user_idx
    ON public.onboarding_temp_password_events (user_id, created_at DESC);

-- Called only by the admin-invite Edge Function using the service role. Reissuing replaces
-- and invalidates the previous temporary password immediately.
CREATE OR REPLACE FUNCTION public.issue_onboarding_temp_password(
    p_user_id uuid,
    p_temp_password text,
    p_generated_by uuid
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_expires_at timestamptz := timezone('utc', now()) + interval '3 days';
BEGIN
    IF coalesce(length(p_temp_password), 0) < 16 THEN
        RAISE EXCEPTION 'Temporary passwords must contain at least 16 characters.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.id = p_user_id
          AND u.is_active
          AND u.deleted_at IS NULL
          AND NOT u.onboarding_completed
          AND u.role IN ('invitee', 'requester')
    ) THEN
        RAISE EXCEPTION 'The account is not waiting for onboarding.';
    END IF;

    INSERT INTO public.onboarding_temp_passwords AS otp (
        user_id,
        password_hash,
        expires_at,
        consumed_at,
        failed_attempts,
        locked_until,
        generated_by,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        extensions.crypt(p_temp_password, extensions.gen_salt('bf', 12)),
        v_expires_at,
        NULL,
        0,
        NULL,
        p_generated_by,
        timezone('utc', now()),
        timezone('utc', now())
    )
    ON CONFLICT (user_id) DO UPDATE SET
        password_hash = EXCLUDED.password_hash,
        expires_at = EXCLUDED.expires_at,
        consumed_at = NULL,
        failed_attempts = 0,
        locked_until = NULL,
        generated_by = EXCLUDED.generated_by,
        created_at = EXCLUDED.created_at,
        updated_at = EXCLUDED.updated_at;

    INSERT INTO public.onboarding_temp_password_events (user_id, event_type, actor_id)
    VALUES (p_user_id, 'issued', p_generated_by);

    RETURN jsonb_build_object('ok', true, 'expiresAt', v_expires_at);
END;
$$;

REVOKE ALL ON FUNCTION public.issue_onboarding_temp_password(uuid, text, uuid)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.issue_onboarding_temp_password(uuid, text, uuid)
    TO service_role;

-- The onboarding-claim Edge Function calls this before setting the permanent Auth password.
-- Every failure deliberately has the same external reason so the endpoint cannot enumerate
-- invited addresses. Five bad attempts lock this credential for fifteen minutes.
CREATE OR REPLACE FUNCTION public.consume_onboarding_temp_password(
    p_email text,
    p_temp_password text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO ''
AS $$
DECLARE
    v_user auth.users%ROWTYPE;
    v_profile public.users%ROWTYPE;
    v_credential public.onboarding_temp_passwords%ROWTYPE;
    v_attempts integer;
BEGIN
    SELECT au.* INTO v_user
    FROM auth.users au
    WHERE lower(au.email) = lower(trim(coalesce(p_email, '')))
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_credentials');
    END IF;

    SELECT * INTO v_profile
    FROM public.users u
    WHERE u.id = v_user.id
      AND u.is_active
      AND u.deleted_at IS NULL
      AND NOT u.onboarding_completed
      AND u.role IN ('invitee', 'requester');

    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_credentials');
    END IF;

    SELECT * INTO v_credential
    FROM public.onboarding_temp_passwords otp
    WHERE otp.user_id = v_user.id
    FOR UPDATE;

    IF NOT FOUND
       OR v_credential.consumed_at IS NOT NULL
       OR v_credential.expires_at <= timezone('utc', now())
       OR v_credential.locked_until > timezone('utc', now()) THEN
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_credentials');
    END IF;

    IF extensions.crypt(coalesce(p_temp_password, ''), v_credential.password_hash)
       <> v_credential.password_hash THEN
        v_attempts := v_credential.failed_attempts + 1;
        UPDATE public.onboarding_temp_passwords
        SET failed_attempts = CASE WHEN v_attempts >= 5 THEN 0 ELSE v_attempts END,
            locked_until = CASE
                WHEN v_attempts >= 5 THEN timezone('utc', now()) + interval '15 minutes'
                ELSE NULL
            END,
            updated_at = timezone('utc', now())
        WHERE user_id = v_user.id;
        RETURN jsonb_build_object('ok', false, 'reason', 'invalid_credentials');
    END IF;

    UPDATE public.onboarding_temp_passwords
    SET consumed_at = timezone('utc', now()),
        failed_attempts = 0,
        locked_until = NULL,
        updated_at = timezone('utc', now())
    WHERE user_id = v_user.id;

    INSERT INTO public.onboarding_temp_password_events (user_id, event_type, actor_id)
    VALUES (v_user.id, 'consumed', v_user.id);

    RETURN jsonb_build_object(
        'ok', true,
        'userId', v_user.id,
        'email', lower(v_user.email),
        'teamId', v_user.raw_user_meta_data->>'team_id'
    );
END;
$$;

REVOKE ALL ON FUNCTION public.consume_onboarding_temp_password(text, text)
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_onboarding_temp_password(text, text)
    TO service_role;
