-- The two dead ends in the sign-in flow, and the way out of each.
--
-- Losing the authenticator was unrecoverable: the login screen asks for a code, the only
-- thing that produces one is gone, and the screen where 2FA can be switched off sits behind
-- that same code. Nothing short of an admin with the service key could break the loop.
--
-- GoTrue has no notion of backup codes, and nothing but GoTrue can mint an aal2 token, so a
-- recovery code cannot stand in for the six digits -- it can only remove the factor that is
-- demanding them. That is what redeem_mfa_recovery_code does: spend a one-time code, drop
-- the factor, and land the person in the app at aal1 with 2FA off and a prompt to set it up
-- again. Still two things to present (the password got them this far, the code finishes it),
-- and a code that has been spent is spent.
--
-- The codes are stored as SHA-256 of their normalised text. They are 48 bits of server-side
-- randomness rather than anything a person chose, so a fast hash is the right one -- there
-- is no dictionary to run against them, and mfa_recovery_attempts caps the online guessing
-- at ten wrong answers an hour.
--
-- verify_current_password is the smaller repair at the other end. Change Password used to
-- check the old password by signing in with it again, and a password sign-in always issues
-- a fresh aal1 session -- so saving a new password quietly threw away the 2FA proof the
-- session already had and bounced the user back to the code prompt mid-flow. Comparing the
-- hash here answers the same question without touching the session.

CREATE TABLE IF NOT EXISTS public.mfa_recovery_codes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    code_hash text NOT NULL,
    used_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mfa_recovery_codes_user_idx
    ON public.mfa_recovery_codes (user_id) WHERE used_at IS NULL;

CREATE TABLE IF NOT EXISTS public.mfa_recovery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    succeeded boolean NOT NULL,
    attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mfa_recovery_attempts_user_idx
    ON public.mfa_recovery_attempts (user_id, attempted_at DESC);

-- Neither table is ever read from the client. RLS with no policy at all is the flat "no",
-- and the REVOKE is belt and braces for a database where the blanket grants to anon and
-- authenticated have a habit of coming back.
ALTER TABLE public.mfa_recovery_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mfa_recovery_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.mfa_recovery_codes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.mfa_recovery_attempts FROM PUBLIC, anon, authenticated;

-- Normalised before hashing so the code works however it was copied: spaces, the dash in
-- the middle and the case all stop mattering.
CREATE OR REPLACE FUNCTION public.mfa_recovery_code_hash(p_code text)
    RETURNS text
    LANGUAGE sql IMMUTABLE
    SET search_path TO ''
    AS $$
    SELECT encode(sha256(upper(regexp_replace(coalesce(p_code, ''), '[^0-9A-Za-z]', '', 'g'))::bytea), 'hex');
$$;

REVOKE ALL ON FUNCTION public.mfa_recovery_code_hash(text) FROM PUBLIC, anon, authenticated;

-- Ten codes, shown once and never again -- only their hashes are kept. Generating replaces
-- whatever was there, so the sheet someone printed last year stops working the moment they
-- ask for a new one.
CREATE OR REPLACE FUNCTION public.generate_mfa_recovery_codes()
    RETURNS SETOF text
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
DECLARE
    v_user uuid := auth.uid();
    v_code text;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'You must be signed in.';
    END IF;

    DELETE FROM public.mfa_recovery_codes WHERE user_id = v_user;

    FOR i IN 1..10 LOOP
        -- 12 hex characters, 48 bits, in two halves for the sake of whoever types it back in.
        v_code := substr(replace(gen_random_uuid()::text, '-', ''), 1, 6)
               || '-'
               || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6);

        INSERT INTO public.mfa_recovery_codes (user_id, code_hash)
        VALUES (v_user, public.mfa_recovery_code_hash(v_code));

        RETURN NEXT v_code;
    END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.generate_mfa_recovery_codes() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.generate_mfa_recovery_codes() TO authenticated;

-- How many are left, for the Security Settings panel. Never the codes themselves.
CREATE OR REPLACE FUNCTION public.my_mfa_recovery_code_status()
    RETURNS jsonb
    LANGUAGE sql SECURITY DEFINER STABLE
    SET search_path TO ''
    AS $$
    SELECT jsonb_build_object(
        'total', count(*),
        'unused', count(*) FILTER (WHERE used_at IS NULL),
        'generatedAt', max(created_at)
    )
    FROM public.mfa_recovery_codes
    WHERE user_id = auth.uid();
$$;

REVOKE ALL ON FUNCTION public.my_mfa_recovery_code_status() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.my_mfa_recovery_code_status() TO authenticated;

-- Spend a code and take the factor with it. auth.uid() throughout: the argument is the code
-- and nothing else, so there is no id a caller could pass to reach another account.
CREATE OR REPLACE FUNCTION public.redeem_mfa_recovery_code(p_code text)
    RETURNS jsonb
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO ''
    AS $$
DECLARE
    v_user uuid := auth.uid();
    v_failures integer;
    v_id uuid;
    v_removed integer;
BEGIN
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'You must be signed in.';
    END IF;

    SELECT count(*) INTO v_failures
    FROM public.mfa_recovery_attempts
    WHERE user_id = v_user
      AND NOT succeeded
      AND attempted_at > now() - interval '1 hour';

    IF v_failures >= 10 THEN
        RAISE EXCEPTION 'Too many recovery attempts. Try again in an hour.';
    END IF;

    SELECT id INTO v_id
    FROM public.mfa_recovery_codes
    WHERE user_id = v_user
      AND used_at IS NULL
      AND code_hash = public.mfa_recovery_code_hash(p_code)
    LIMIT 1;

    IF v_id IS NULL THEN
        INSERT INTO public.mfa_recovery_attempts (user_id, succeeded) VALUES (v_user, false);
        RETURN jsonb_build_object('ok', false);
    END IF;

    UPDATE public.mfa_recovery_codes SET used_at = now() WHERE id = v_id;

    -- Every factor, not just the one that happened to be verified: a half-finished
    -- enrolment left behind would otherwise put the account straight back into the loop.
    DELETE FROM auth.mfa_factors WHERE user_id = v_user;
    GET DIAGNOSTICS v_removed = ROW_COUNT;

    -- The remaining codes only ever existed to unlock a factor that is now gone. Re-enrolling
    -- issues a fresh set.
    DELETE FROM public.mfa_recovery_codes WHERE user_id = v_user;
    INSERT INTO public.mfa_recovery_attempts (user_id, succeeded) VALUES (v_user, true);

    RETURN jsonb_build_object('ok', true, 'factorsRemoved', v_removed);
END;
$$;

REVOKE ALL ON FUNCTION public.redeem_mfa_recovery_code(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.redeem_mfa_recovery_code(text) TO authenticated;

-- Is this the caller's current password? Only ever about the caller, and only ever yes or no.
--
-- pgcrypto lives in the extensions schema on a stock Supabase project, but has been known to
-- sit in public on older ones; both are on the search_path, extensions first, so crypt()
-- resolves either way. Unquoted deliberately: 'extensions, public' in quotes is read as one
-- schema by that name, and nothing in it resolves at all.
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

CREATE OR REPLACE FUNCTION public.verify_current_password(p_password text)
    RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER STABLE
    SET search_path TO extensions, public
    AS $$
DECLARE
    v_hash text;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'You must be signed in.';
    END IF;

    IF coalesce(p_password, '') = '' THEN
        RETURN false;
    END IF;

    SELECT encrypted_password INTO v_hash FROM auth.users WHERE id = auth.uid();

    -- An invited user who has not set one yet. There is nothing to match, and nothing to leak.
    IF coalesce(v_hash, '') = '' THEN
        RETURN false;
    END IF;

    RETURN crypt(p_password, v_hash) = v_hash;
END;
$$;

REVOKE ALL ON FUNCTION public.verify_current_password(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.verify_current_password(text) TO authenticated;
